meta_product_name: "Fundeat"
meta_title: "FUND your local places where you enjoy to EAT"
meta_description: "RFundeat enables Restaurants to easily raise money and gives private investors the opportunity to sustainably invest in their local community"
meta_image: "app/assets/images/fundeat-logo.png" # should exist in `app/assets/images/`
